basic_app/urls.py
from django.urls import path
from basic_app import views
from django.conf import settings
from django.conf.urls.static import static




app_name = 'basic_app'

urlpatterns = [
	path('', views.HomeView.as_view(), name='home'),
	path('list/', views.ProfileListView.as_view(), name='list'),
	path('detail/<int:pk>/', views.ProfileDetailView.as_view(), name='detail'),
	path('create/', views.ProfileCreateView.as_view(), name='create'),
	path('update/<int:pk>/', views.ProfileUpdateView.as_view(), name='update'),
	path('delete/<int:pk>/',views.ProfileDeleteView.as_view(), name='delete')
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profilelog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basic_app.urls'))
]

basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Profile(models.Model):
	first_name =  models.CharField(max_length=123, null=True)
	last_name =  models.CharField(max_length=123, null=True)
	email =  models.EmailField(null=True)
	phone_number = models.IntegerField()
	passport = models.ImageField(upload_to='passport_pic', blank=True)
	country =  models.CharField(max_length=123, null=True)
	address =  models.CharField(max_length=123, null=True)
	next_of_kin_name =  models.CharField(max_length=123, null=True)
	next_of_kin_email =  models.EmailField(null=True)

	def get_absolute_url(self):
		return reverse ('basic_app:detail', kwargs={'pk':self.pk})

	def __str__(self): 
		name = f'{self.last_name} {self.first_name}'
		return name

basic_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from basic_app.models import Profile
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

# Create your views here.

class HomeView(TemplateView):
	template_name = 'basic_app/home.html'

class ProfileListView(ListView):
	model = Profile

class ProfileDetailView(DetailView):
	model = Profile

class ProfileCreateView(CreateView):
	model = Profile
	fields = '__all__'

class ProfileUpdateView(UpdateView):
	model = Profile
	fields = '__all__'

class ProfileDeleteView(DeleteView):
	model = Profile
	context_object_name = 'profile_delete'
	success_url = reverse_lazy('basic_app:list') 

basic_app/templates/basic_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <link rel="stylesheet" type="text/css" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
  <title>PROFILE LOG</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'basic_app:home' %}">Home</a>
      </li>

    </ul>
  </div>

</nav>
<div class="container">

{% block content %}
{% endblock content %}

</div>




</body>
</html>

basic_app/templates/basic_app/home.html
{% extends 'basic_app/base.html' %}

{% block content %}

<div class="jumbotron">

	<h1>Profile Log</h1>
	
</div>


<a class="btn btn-primary btn-lg" href="{% url 'basic_app:list' %}">Names</a>

{% endblock content %}

basic_app/templates/basic_app/profile_confirm_delete.html
{% extends 'basic_app/base.html' %}



{% block content %}

<div class="container jumbotron">

<h1>Are you sure you want to delete {{profile_delete.last_name}}'s Profile</h1>

<form method="POST">
	{% csrf_token %}
	<p><input class="btn btn-danger" type="submit" value="Confirm"></p>
	<p><a class="btn btn-warning" href="{% url 'basic_app:detail' profile_delete.id %}">Cancel</a></p>
</form>


</div>

{% endblock content %}

basic_app/templates/basic_app/profile_detail.html
{% extends 'basic_app/base.html' %}

{% block content %}

<h1>{{profile.last_name}}'s Profile</h1>

<div class="jumbotron">

		<p><h1>Passport: <img src="{{profile.passport.url}}"></h1></p>
		<p><h1>First Name: {{profile.first_name}}</h1></p>
		<p><h1>Last Name: {{profile.last_name}}</h1></p>
		<p><h1>Email: {{profile.email}}</h1></p>
		<p><h1>Phone Number: {{profile.phone_number}}</h1></p>
		<p><h1>Country: {{profile.country}}</h1></p>
		<p><h1>Address: {{profile.address}}</h1></p>
		<p><h1>Next of Kin's Name: {{profile.next_of_kin_name}}</h1></p>
		<p><h1>Next of Kin's Email: {{profile.next_of_kin_email}}</h1></p>
		
		
	
	


		

</div>
<p>
<a class="btn btn-warning btn-lg" href="{% url 'basic_app:update' profile.id %}">Update {{profile.last_name}}'s profile</a>
</p>


<p>
<a class="btn btn-danger btn=lg" href="{% url 'basic_app:delete' profile.id %}">Delete {{profile.last_name}}'s profile</a>
</p>

<p>
	<a class="btn btn-primary btn-lg" href="{% url 'basic_app:list' %}">Back</a>
</p>
{% endblock content %}

basic_app/templates/basic_app/profile_form.html
{% extends 'basic_app/base.html' %}


{%  block content %}

{% if not form.instance.pk %}
  <h1>Create Profile</h1>
{% else %}
  <h1>Update Profile</h1>
{% endif %}


<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <p>
  	<input type="submit" class='btn btn-warning '  value="Submit" name="" id="">     
  </p>
</form>

<a class="btn btn-primary btn-lg" href="{% url 'basic_app:list' %}">Back</a>

{% endblock content %}

basic_app/templates/basic_app/profile_list.html
{% extends 'basic_app/base.html' %}

{% block content %}

<div class="jumbotron">
	
	<ol>
		{% for names in profile_list %}
			<h1><li><a href="{% url 'basic_app:detail' names.id %}">{{names}}</a></li></h1>
		{% endfor %}
	</ol>


</div>

<a class="btn btn-primary btn-lg" href="{% url 'basic_app:create' %}">Create New Profile</a>

{% endblock content %}